import json
import worldometer

def get_worldometer_data():
    data = {
        'abortions_this_year': worldometer.abortions_this_year()['abortions_this_year'],
        'bicycles_produced_this_year': worldometer.bicycles_produced_this_year()['bicycles_produced_this_year'],
        'births_this_year': worldometer.births_this_year()['births_this_year'],
        'births_today': worldometer.births_today()['births_today'],
        'blog_posts_written_today': worldometer.blog_posts_written_today()['blog_posts_written_today'],
        'cars_produced_this_year': worldometer.cars_produced_this_year()['cars_produced_this_year'],
        'cellular_phones_sold_today': worldometer.cellular_phones_sold_today()['cellular_phones_sold_today'],
        'cigarettes_smoked_today': worldometer.cigarettes_smoked_today()['cigarettes_smoked_today'],
        'co2_emissions_this_year': worldometer.co2_emissions_this_year()['co2_emissions_this_year'],
        'coal_left': worldometer.coal_left()['coal_left'],
        'communicable_disease_deaths_this_year': worldometer.communicable_disease_deaths_this_year()['communicable_disease_deaths_this_year'],
        'computers_produced_this_year': worldometer.computers_produced_this_year()['computers_produced_this_year'],
        'current_world_population': worldometer.current_world_population()['current_world_population'],
        'days_to_the_end_of_coal': worldometer.days_to_the_end_of_coal()['days_to_the_end_of_coal'],
        'days_to_the_end_of_natural_gas': worldometer.days_to_the_end_of_natural_gas()['days_to_the_end_of_natural_gas'],
        'days_to_the_end_of_oil': worldometer.days_to_the_end_of_oil()['days_to_the_end_of_oil'],
        'deaths_caused_by_alcohol_this_year': worldometer.deaths_caused_by_alcohol_this_year()['deaths_caused_by_alcohol_this_year'],
        'deaths_caused_by_cancer_this_year': worldometer.deaths_caused_by_cancer_this_year()['deaths_caused_by_cancer_this_year'],
        'deaths_caused_by_hiv_aids_this_year': worldometer.deaths_caused_by_hiv_aids_this_year()['deaths_caused_by_hiv/aids_this_year'],
        'deaths_caused_by_malaria_this_year': worldometer.deaths_caused_by_malaria_this_year()['deaths_caused_by_malaria_this_year'],
        'deaths_caused_by_smoking_this_year': worldometer.deaths_caused_by_smoking_this_year()['deaths_caused_by_smoking_this_year'],
        'deaths_caused_by_water_related_diseases_this_year': worldometer.deaths_caused_by_water_related_diseases_this_year()['deaths_caused_by_water_related_diseases_this_year'],
        'deaths_of_children_under_5_this_year': worldometer.deaths_of_children_under_5_this_year()['deaths_of_children_under_5_this_year'],
        'deaths_of_mothers_during_birth_this_year': worldometer.deaths_of_mothers_during_birth_this_year()['deaths_of_mothers_during_birth_this_year'],
        'deaths_this_year': worldometer.deaths_this_year()['deaths_this_year'],
        'deaths_today': worldometer.deaths_today()['deaths_today'],
        'desertification_this_year': worldometer.desertification_this_year()['desertification_this_year'],
        'emails_sent_today': worldometer.emails_sent_today()['emails_sent_today'],
        'energy_used_today': worldometer.energy_used_today()['energy_used_today'],
        'forest_loss_this_year': worldometer.forest_loss_this_year()['forest_loss_this_year'],
        'google_searches_today': worldometer.google_searches_today()['google_searches_today'],
        'hiv_aids_infected_people': worldometer.hiv_aids_infected_people()['hiv/aids_infected_people'],
        'internet_users_in_the_world_today': worldometer.internet_users_in_the_world_today()['internet_users_in_the_world_today'],
        'land_lost_to_soil_erosion_this_year': worldometer.land_lost_to_soil_erosion_this_year()['land_lost_to_soil_erosion_this_year'],
        'money_spent_for_obesity_related_diseases_in_the_usa_today': worldometer.money_spent_for_obesity_related_diseases_in_the_usa_today()['money_spent_for_obesity_related_diseases_in_the_usa_today'],
        'money_spent_on_illegal_drugs_this_year': worldometer.money_spent_on_illegal_drugs_this_year()['money_spent_on_illegal_drugs_this_year'],
        'money_spent_on_videogames_today': worldometer.money_spent_on_videogames_today()['money_spent_on_videogames_today'],
        'money_spent_on_weight_loss_programs_in_the_usa_today': worldometer.money_spent_on_weight_loss_programs_in_the_usa_today()['money_spent_on_weight_loss_programs_in_the_usa_today'],
        'natural_gas_left': worldometer.natural_gas_left()['natural_gas_left'],
        'net_population_growth_this_year': worldometer.net_population_growth_this_year()['net_population_growth_this_year'],
        'net_population_growth_today': worldometer.net_population_growth_today()['net_population_growth_today'],
        'new_book_titles_published_this_year': worldometer.new_book_titles_published_this_year()['new_book_titles_published_this_year'],
        'newspapers_circulated_today': worldometer.newspapers_circulated_today()['newspapers_circulated_today'],
        'non_renewable_sources': worldometer.non_renewable_sources()['non-renewable_sources'],
        'obese_people_in_the_world': worldometer.obese_people_in_the_world()['obese_people_in_the_world'],
        'oil_left': worldometer.oil_left()['oil_left'],
        'oil_pumped_today': worldometer.oil_pumped_today()['oil_pumped_today'],
        'overweight_people_in_the_world': worldometer.overweight_people_in_the_world()['overweight_people_in_the_world'],
        'people_who_died_of_hunger_today': worldometer.people_who_died_of_hunger_today()['people_who_died_of_hunger_today'],
        'people_with_no_access_to_a_safe_drinking_water_source': worldometer.people_with_no_access_to_a_safe_drinking_water_source()['people_with_no_access_to_a_safe_drinking_water_source'],
        'public_education_expenditure_today': worldometer.public_education_expenditure_today()['public_education_expenditure_today'],
        'public_healthcare_expenditure_today': worldometer.public_healthcare_expenditure_today()['public_healthcare_expenditure_today'],
        'public_military_expenditure_today': worldometer.public_military_expenditure_today()['public_military_expenditure_today'],
        'renewable_sources': worldometer.renewable_sources()['renewable_sources'],
        'road_traffic_accident_fatalities_this_year': worldometer.road_traffic_accident_fatalities_this_year()['road_traffic_accident_fatalities_this_year'],
        'seasonal_flu_deaths_this_year': worldometer.seasonal_flu_deaths_this_year()['seasonal_flu_deaths_this_year'],
        'solar_energy_striking_earth_today': worldometer.solar_energy_striking_earth_today()['solar_energy_striking_earth_today'],
        'suicides_this_year': worldometer.suicides_this_year()['suicides_this_year'],
        'toxic_chemicals_released_in_the_environment_this_year': worldometer.toxic_chemicals_released_in_the_environment_this_year()['toxic_chemicals_released_in_the_environment_this_year'],
        'tv_sets_sold_worldwide_today': worldometer.tv_sets_sold_worldwide_today()['tv_sets_sold_worldwide_today'],
        'tweets_sent_today': worldometer.tweets_sent_today()['tweets_sent_today'],
        'undernourished_people_in_the_world': worldometer.undernourished_people_in_the_world()['undernourished_people_in_the_world'],
        'water_used_this_year': worldometer.water_used_this_year()['water_used_this_year'],
    }

    return json.dumps(data)

if __name__ == "__main__":
    print(get_worldometer_data())
